name: Refresh

on: workflow_dispatch

jobs:
  Review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install playwright
          python -m playwright install chromium
      - name: Simulate Display
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1920x1080x24 &
      - name: Review Game
        run: |
          python -u refresh.py
        env:
            DISPLAY: ":99.0"
      - name: Log in as Action Bot
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Push
        run: |
          git add .
          git commit -m "Deployed from Workflow ${{ github.run_id }}"
          git push